version: '3.3'
services:
  mongodb:
    image: mongo
    volumes:
      - mongodata-natours:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  mongodata-natours:
